-- AlterTable
ALTER TABLE `dapem` MODIFY `dropping_status` ENUM('DRAFT', 'CANCEL', 'PENDING', 'PROCCESS', 'APPROVED', 'PAID_OFF') NOT NULL DEFAULT 'DRAFT',
    MODIFY `takeover_status` ENUM('DRAFT', 'CANCEL', 'PENDING', 'PROCCESS', 'APPROVED', 'PAID_OFF') NOT NULL DEFAULT 'DRAFT',
    MODIFY `mutasi_status` ENUM('DRAFT', 'CANCEL', 'PENDING', 'PROCCESS', 'APPROVED', 'PAID_OFF') NOT NULL DEFAULT 'DRAFT',
    MODIFY `cash_status` ENUM('DRAFT', 'CANCEL', 'PENDING', 'PROCCESS', 'APPROVED', 'PAID_OFF') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `debitur` MODIFY `pay_office` VARCHAR(191) NULL;
