import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Impor ConfigProvider dari antd
import { App, ConfigProvider } from "antd";
// import { UserProvider } from "@/components/contexts/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: `SYREL | ${
    process.env.NEXT_PUBLIC_APP_SHORTNAME || "PEMBIAYAAN PENSIUN"
  }`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Gunakan ConfigProvider untuk mengaplikasikan font ke komponen Ant Design */}
        <ConfigProvider
          theme={{
            token: {
              // Setel fontFamily menggunakan variabel CSS Next.js font
              fontFamily: "var(--font-geist-mono)",
            },
          }}
        >
          <App>
            {/* <UserProvider> */}
            {children}
            {/* </UserProvider> */}
          </App>
        </ConfigProvider>
      </body>
    </html>
  );
}
